### ISSUE TITLE
Cannot use a custom database schema name

### ISSUE THREAD

**Issue by Chralu** [notum-cz/strapi-plugin-location#14] opened 2023-08-01 13:52 UTC
### Describe the bug

Using Postgres 15.3, with a schema different from the default one (`public`), `location` fields cannot be created.

This error doesn't seem to happen when using the default `public` schema.

### Steps to reproduce the behavior

1. On your Postgres instance, create a new schema ( `CREATE SCHEMA IF NOT EXISTS strapi;`) 
2. Setup Strapi to use that schema.
3. Add the `strapi-plugin-location` plugin to Strapi
4. In the **Content-Type builder**, create a type with a `location` field
5. apply changes

### Expected behavior

Strapi restarts and the database is updated

### Actual behavior

Strapi restart fails with the following error : 

```log 
error: 
              ALTER TABLE user_profiles
              ADD COLUMN address_geopoint_geom GEOMETRY(Point, 4326);
             - relation "user_profiles" does not exist
```

**Comment by omikulcik** [comment] 2023-08-08 09:35
Hi @Chralu, I was unfortunately unable to reproduce this bug. I followed the steps you have provided and everything went through just fine. Please, see the screenshot attached.

![image](https://github.com/notum-cz/strapi-plugin-location/assets/44231035/47ce68bf-e77b-478c-9d6f-372e28286158)

Have you used Postgres with the Postgis extension?

**Comment by omikulcik** [comment] 2023-09-13 12:45
@Chralu, do you please have any updates on this or can I close this issue?

**Comment by omikulcik** [comment] 2023-12-06 12:09
Closed for inactivity

**Closed by omikulcik** 2023-12-06 12:09 UTC
Labels: issue: bug, status: can not reproduce, severity: low
