### ISSUE TITLE
Error installing plugin Cannot find module './server'

### ISSUE THREAD

**Issue by ingyesid** [notum-cz/strapi-plugin-location#134] opened 2024-02-07 03:02 UTC
I am trying to use the plugin following the official guide but i am getting the following error

`Error: Could not load js config file                                                                           ││   /home/folks/node_modules/@notum-cz/strapi-plugin-location/strapi-server.js: Cannot find module './server'      ││   Require stack:                                                                                                 ││   - /home/folks/node_modules/@notum-cz/strapi-plugin-location/strapi-server.js                                   ││   - /home/folks/node_modules/@strapi/utils/dist/index.js                                                         ││   - /home/folks/node_modules/@strapi/strapi/dist/commands/actions/admin/create-user/action.js                    ││   - /home/folks/node_modules/@strapi/strapi/dist/commands/actions/admin/create-user/command.js                   ││   - /home/folks/node_modules/@strapi/strapi/dist/commands/index.js                                               ││   - /home/folks/node_modules/@strapi/strapi/dist/cli.js                                                          ││   - /home/folks/node_modules/@strapi/strapi/bin/strapi.js                                                        ││   at loadJsFile                                                                                                  ││   (/home/folks/node_modules/@strapi/strapi/dist/core/app-configuration/load-config-file.js:18:13)                ││   at Module.loadFile                                                                                             ││   (/home/folks/node_modules/@strapi/strapi/dist/core/app-configuration/load-config-file.js:37:14)                ││   at Object.loadPlugins (/home/folks/node_modules/@strapi/strapi/dist/core/loaders/plugins/index.js:90:41)       ││   at async Strapi.loadPlugins (/home/folks/node_modules/@strapi/strapi/dist/Strapi.js:311:5)                     ││   at async Promise.all (index 3)                                                                                 ││   at async Strapi.register (/home/folks/node_modules/@strapi/strapi/dist/Strapi.js:341:5)                        ││   at async Strapi.load (/home/folks/node_modules/@strapi/strapi/dist/Strapi.js:425:5)                            ││   at async Object.develop (/home/folks/node_modules/@strapi/admin/dist/_chunks/index-sNH2VWbC.js:837:28)         ││   at async develop (/home/folks/node_modules/@strapi/admin/dist/_chunks/develop-YNTGWKMC.js:61:5)                ││   at async Command.parseAsync (/home/folks/node_modules/commander/lib/command.js:923:5)       `

### Screenshots
![Screenshot 2024-02-06 at 10 01 41 PM](https://github.com/notum-cz/strapi-plugin-location/assets/1714607/0daa447b-0b5f-4486-9bdc-fc8cec5e14a8)

### System

- Node.js version: v20.11.0
- NPM version: 0.2.4
- Strapi version: v4.19.1
- Database: Postgress
- Operating system: ubuntu 22.04

**Comment by Bastiendsp** [comment] 2024-02-09 09:44
hi, same

**Comment by pturner1989** [comment] 2024-02-09 12:40
I also had this. There's a bunch of peer dependencies not listed on the installation instructions, you need to add these separately then it worked:

`yarn add @babel/runtime@>=7.11.0 @codemirror/lint@>=6.0.0 @codemirror/state@>=6.0.0 @codemirror/theme-one-dark@>=6.0.0 @codemirror/view@>=6.0.0 codemirror@>=6.0.0 @codemirror/autocomplete@>=6.0.0 @codemirror/language@>=6.0.0 @codemirror/search@>=6.0.0 @codemirror/view@>=6.0.0 @lezer/common@^1.0.0`


This was the warnings on installing strapi-plugin-loction:

```
yarn install v1.22.21
warning ../package.json: No license field
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "@notum-cz/strapi-plugin-location > @strapi/design-system > @uiw/react-codemirror@4.21.21" has unmet peer dependency "@babel/runtime@>=7.11.0".
warning "@notum-cz/strapi-plugin-location > @strapi/design-system > @uiw/react-codemirror@4.21.21" has unmet peer dependency "@codemirror/state@>=6.0.0".
warning "@notum-cz/strapi-plugin-location > @strapi/design-system > @uiw/react-codemirror@4.21.21" has unmet peer dependency "@codemirror/theme-one-dark@>=6.0.0".
warning "@notum-cz/strapi-plugin-location > @strapi/design-system > @uiw/react-codemirror@4.21.21" has unmet peer dependency "@codemirror/view@>=6.0.0".
warning "@notum-cz/strapi-plugin-location > @strapi/design-system > @uiw/react-codemirror@4.21.21" has unmet peer dependency "codemirror@>=6.0.0".
warning "@notum-cz/strapi-plugin-location > @strapi/design-system > @uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.21.21" has unmet peer dependency "@codemirror/autocomplete@>=6.0.0".
warning "@notum-cz/strapi-plugin-location > @strapi/design-system > @uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.21.21" has unmet peer dependency "@codemirror/language@>=6.0.0".
warning "@notum-cz/strapi-plugin-location > @strapi/design-system > @uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.21.21" has unmet peer dependency "@codemirror/lint@>=6.0.0".
warning "@notum-cz/strapi-plugin-location > @strapi/design-system > @uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.21.21" has unmet peer dependency "@codemirror/search@>=6.0.0".
warning "@notum-cz/strapi-plugin-location > @strapi/design-system > @uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.21.21" has unmet peer dependency "@codemirror/view@>=6.0.0".
warning "@notum-cz/strapi-plugin-location > @strapi/design-system > @uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup > @codemirror/autocomplete@6.12.0" has unmet peer dependency "@lezer/common@^1.0.0".

```

**Comment by ingyesid** [comment] 2024-02-10 17:07
@pturner1989 how can i do that using npm or can i use both of them in my project?

**Comment by raniaamina** [comment] 2024-02-12 02:37
it still happen

**Comment by FaijanSaifi99** [comment] 2024-02-14 06:10
any update on this ?

**Comment by FaijanSaifi99** [comment] 2024-02-14 06:23
@raniaamina do you any other option for managing and querying the latitude and logitude.

**Comment by raniaamina** [comment] 2024-02-14 06:25
> @raniaamina do you know any other option for managing and querying the latitude and logitude.
> 
> 
> 

Currently just save it as string.

**Comment by FaijanSaifi99** [comment] 2024-02-14 06:27
> > @raniaamina do you know any other option for managing and querying the latitude and logitude.
> 
> Currently just save it as string.

are you using filtering based on the latitude and longitude

**Comment by raniaamina** [comment] 2024-02-14 06:31
> > > @raniaamina do you know any other option for managing and querying the latitude and logitude.
> > 
> > Currently just save it as string.
> 
> are you using filtering based on the latitude and longitude
> 

It depend on what front end need, simply use regex if you wanna filter the format. This one of them;
https://ihateregex.io/expr/lat-long/

Btw, this conversation is out of topic issue, imo.

**Comment by ingyesid** [comment] 2024-02-14 16:28
Still not working ... and i already installed the dependencies listed on @pturner1989 comment :(

**Comment by devMaster28** [comment] 2024-02-19 21:51
hi, any news ?

**Comment by FaijanSaifi99** [comment] 2024-02-20 13:10
If you want to use location based filtering you can do it with custome code

First enable the postgis extension in postgres database and the customize the endpoint like this

SELECT
  id,
  name
FROM
  public.store
WHERE
  ST_DWithin(
    ST_Transform(ST_SetSRID(ST_MakePoint(77.3433442537524, 28.58118352566312), 4326), 3857),
    ST_Transform(ST_SetSRID(ST_MakePoint(longitude, latitude), 4326), 3857), 1000)
ORDER BY
  distance;

**Comment by kaechele** [comment] 2024-03-01 16:57
This is a duplicate of #126

**Comment by earnedo1991** [comment] 2024-03-02 11:51
hi, any news ?

**Comment by omikulcik** [comment] 2024-03-19 09:08
Hi, it should be fixed! :)

**Closed by omikulcik** 2024-03-19 09:08 UTC

**Comment by ArtKuz** [comment] 2025-07-02 12:26
Same problem in Strapi v4.25.1 and v4.25.22
